### ISSUE TITLE
hw3_release Extra Credit: Stitching Multiple Images?

### ISSUE THREAD

**Issue by lgqfhwy** [nizihabi/Stanford_CS131_HW#1]
Hello, I am a beginner. In hw3_release Extra Credit: Stitching Multiple Images, I don't know how to do.
The problem said given a sequence of m images, then stitch an ordered chain of images. I want to take the first and second images then stitch together, formed a new images, then stitch together the third images. But it is too complex and maybe have some simple ways.
I notice that you haven't do this problem, if you have any idea, please complete the code. I am a beginner, it is too hard for me. Thank you so much.

**Comment by nizihabi** [comment]
I am a beginner to this course too, and I can only learn this course by my spare time，so I even haven't finished the ppts about SIFT, I'm sorry that I can't solve your problem currently. _(:з」∠)_

**Comment by lgqfhwy** [comment]
This course is hard for me. Maybe we could communicate with each other more hereafter. :)

**Comment by nizihabi** [comment]
I have finished the Extra Credit: Stitching Multiple Images, I don't know  better way to solve this problem, I just convert all relative affine matrix to one coordinate and stitch all images together. If you get better way ,please tell me. Thanks~
